version: "2"
services:
  scrapyd:
    container_name: scrapyd-mitiebot
    image: alexandresgf/scrapyd-service:latest
    environment:
      SCRAPYD_PROJECT_NAME: mitiebot
    ports:
      - 6800:6800
    volumes:
      - .:/home/spidercluster/mitiebot
    networks:
      - mitiebotnet
  #mongo:
    #container_name: mongo-mitiebot
    #image: mongo:latest
    #ports:
      #- 27017:27017
    #networks:
      #- mitiebotnet

networks:
  mitiebotnet:
    driver: bridge
